version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db-fiap
    environment:
      POSTGRES_DB: products_db
      POSTGRES_USER: fiap_tech
      POSTGRES_PASSWORD: 102030
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
